# Generated by Django 5.1 on 2024-08-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='detail_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
